import pandas as pd

df = pd.read_csv('miscellaneous.csv')

Amines and Amides = ['2-Aminobenzimidazole',
 '2-Chloro-2',6'-diethylacetanilide'.
 '2-Chloro-N-(2-ethyl-6-methylphenyl)acetamide',
 '2-(Dimethylamino)-N-hydroxy-2-oxoethanimidothioic acid methyl ester',
 'Acetamide, 2-(diethylamino)-N-(2,6-dimethylphenyl)-']

Fluorinated Compounds = ['11-chloroeicosafluoro-3-oxaundecane-1-sulfonate',
 '11-chloroeicosafluoro-3-oxaundecane-1-sulfonic acid',
 '1-Decanesulfonic acid, 1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,10-heneicosafluoro-',
 '1-Heptanesulfonic acid, 1,1,2,2,3,3,4,4,5,5,6,6,7,7,7-pentadecafluoro-',
 '1-Nonanesulfonic acid, 1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,9-nonadecafluoro-']
Chlorinated Compounds = ['1,1,1,2-Tetrachloroethane',
 '1,1,1-Trichloroethane',
 '1,1,2-Trichloroethane',
 '1,1-Dichloroethane',
 '1,1-Dichloroethene',
 '1,1-Dichloropropanone',
 '1,2,3-Trichloropropane',
 '1,2,4-Trichlorobenzene',
 '1,2-Dibromo-3-chloropropane',
 '1,2-Dichloroethane',
 '1,2-Dichloropropane',
 '2,2',3,3',4,4',5,5',6-Nonachlorobiphenyl',
 '2,2',3,3',4,4',5,5'-Octachlorobiphenyl',
 '2,2',3,3',4,4',5,6,6'-Nonachlorobiphenyl',
 '2,3,3'-Trichlorobiphenyl',
 '2,3,4-Trichlorobiphenyl',
 '2,3,5-Trichlorobiphenyl',
 '2,4,4'-Trichlorobiphenyl',
 '2,4,5-Trichlorobiphenyl',
 '2,4,6-Trichlorobiphenyl',
 '2,4-Dichlorobiphenyl',
 '3,3',4,4',5,5'-Hexachlorobiphenyl',
 '3,3',4,4'-Tetrachlorobiphenyl',
 '4,4'-Dichlorobiphenyl',
 '4,4'-Isopropylidenediphenol',
 '4-Hydroxychlorothalonil']

Alcohols = ['Ethanol','Isopropanol','p-Cresol','Methyl acetate', 'Methyl bromide', 'Nonylphenol di - Ethylbenzene','Dimethoxymethane','D-Limonene','1-Butanol','1-Methoxy-4-(2-propenyl)benzene','1-Octanol','2,4-D','2-Ethylhexanol','2-Methylanthracene','2-Methylnaphthalene',' 4-Nonylphenol diethoxylate','4-Nonylphenol monoethoxylates','4-Nonylphenols']

organic_compounds = [
    '1,2-Dichloroethane-d4',
    '1,3-Butadiene',
    '1,3-Dioxane',
    '1,3-Dioxolane',
    '1,4-Dioxane',
    '1,2,4-Trimethylbenzene',
    '1-Bromo-3-chloropropane-d6',
    'Acetochlor',
    'Acetonitrile',
    'Benzene',
    'Benzo[a]pyrene',
    'Carbaryl',
    'Chlorobenzene',
    'Di(2-ethoxylhexyl) phthalate',
    'Diazepam-D5',
    'Dibenz[a,h]anthracene',
    'Dibenzothiophene',
    'Diethyl phthalate',
    'Dimethoxymethane',
    'D-Limonene',
    'Ethane, 1-chloro-1,1-difluoro-',
    'Ethyl acetate',
    'Ethylbenzene',
    'Fluorene',
    'Fluoranthene',
    'Inorganic nitrogen (nitrate and nitrite)',
    'Isobutyle acetate',
    'Isopropanol',
    'Lipids',
    'Methyl acetate',
    'Methyl bromide',
    'Methylene chloride',
    'Nitrate + Nitrite',
    'Nitrogen',
    'Nonylphenol diethoxylate',
    'Organic carbon',
    'Organic nitrogen',
    'Organic phosphorus',
    'Orthophosphate',
    'p-Cresol',
    'p-Cumylphenol',
    'p-Dichlorobenzene',
    'Pentachloroanisole',
    'Pentachlorobiphenyl',
    'Pentanal',
    'Pentane',
    'Perylene',
    'Phenanthrene',
    'Phenanthridine',
    'Phenazopyridine',
    'Phenol',
    'Phosphorus',
    'Phosphorus, Particulate Organic',
    'Phthalazinone',
    'p-Octylphenol',
    'Propyl acetate',
    'Soluble Reactive Phosphorus (SRP)',
    'Styrene',
    'Toluene',
    'Toluene-d8',
    'Total Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)',
    'Triphenyl phosphate',
    'Vinyl chloride',
    'Volatile suspended solids'
]
Pesticides_Herbicides = [
    "1rs Cis-Permethrin",
    "1H-Pyrazole-3-carboxamide",
    "5-amino-1-[2,6-dichloro-4-(trifluoromethyl) phenyl]-4-[(trifluoromethyl)sulfinyl]-",
    "2-(1-Hydroxyethyl)-6-methylaniline",
    "Acephate",
    "Acetaminophen",
    "Acetaminophen-d3",
    "Acetochlor",
    "Acetochlor-d11",
    "Acetochlor ESA",
    "Acetochlor OA",
    "Acetochlor sulfinylacetic acid",
    "Acetophenone",
    "Acibenzolar-S-methyl",
    "Aldicarb",
    "Aldicarb sulfone",
    "Aldicarb sulfoxide",
    "Aldrin",
    "Alachlor",
    "Alachlor-d13",
    "Alachlor ESA",
    "Alachlor OA",
    "Alachlor sulfinylacetic acid",
    "Ametryn",
    "Amphetamine",
    "Amphetamine-d6",
    "Anthracene",
    "Asulam",
    "Atrazine",
    "Azinphos-methyl",
    "Azinphos-methyl oxygen analog",
    "Benz[a]anthracene",
    "Benzo[e]pyrene",
    "Benzo[ghi]perylene",
    "Benzo[k]fluoranthene",
    "Benzophenone",
    "Benzovindiflupyr",
    "Bromacil",
    "Bromochloromethane",
    "Captan",
    "Carbaryl-d7",
    "Carbendazim",
    "Carbofuran",
    "Carbon disulfide",
    "Carbon tetrachloride",
    "Chloroform",
    "Chloromethane",
    "Chlorantraniliprole",
    "Chlordane",
    "Chlorfenapyr",
    "Chlorothalonil",
    "Chlorpyrifos",
    "Chlorsulfuron",
    "Chlorthal-dimethyl",
    "Chlorthal-Monomethyl",
    "Citalopram",
    "Clonidine",
    "Cumene",
    "Cyclaniliprole",
    "Cyclohexanone",
    "Cyhalofop butyl",
    "Cyproconazole",
    "Cyprodinil",
    "DDT/DDD/DDE, sum of p,p' & o,p' isomers",
    "Deethylatrazine-d6",
    "Deethylhydroxyatrazine",
    "Deltamethrin",
    "Demethylfluometuron",
    "Demethyl hexazinone B",
    "Diazinon",
    "Dicamba",
    "Dieldrin",
    "Dimethachlor sulfonic acid",
    "Dimethenamid",
    "Dimethoate",
    "Dithiopyr",
    "Fenamidone",
    "Fipronil",
    "Fipronil Desulfinyl",
    "Fipronil Sulfide",
    "Fipronil sulfonate",
    "Flonicamid",
    "Fluazinam",
    "Fluopicolide",
    "Glyphosate",
    "Imazalil",
    "Imidacloprid",
    "Imidacloprid desnitro",
    "Malathion",
    "Metolachlor",
    "Nicosulfuron",
    "Oxadiazon",
    "Oxamyl",
    "Pebulate",
    "Pendimethalin",
    "Penoxsulam",
    "Pentachloronitrobenzene",
    "Pentachlorophenol",
    "Penthiopyrad",
    "Phorate",
    "Phorate O.A.",
    "Prodiamine",
    "Profenofos",
    "Prometryn",
    "Propazine",
    "Resmethrin",
    "Sulfentrazone",
    "Sulfometuron methyl",
    "Thiacloprid",
    "Thiamethoxam",
    "Trichlorobiphenyl",
    "Trichloroethylene",
    "Triclopyr"
]
UPDATE c_category 
SET characteristic_group = 'Pharmaceuticals and Personal Care Products' 
WHERE characteristicname ILIKE ANY (ARRAY[
    'Abacavir',
    'Acyclovir',
    'Albuterol',
    'Albuterol-d9',
    'Alprazolam',
    'Amitriptyline',
    'Androsterone',
    'Androsterone glucuronide',
    'Androsterone sulfate',
    'Antipyrine',
    'Caffeine',
    'Caffeine-d9',
    'Caffeine-trimethyl-13C3',
    'Codeine',
    'Desogestrel',
    'Codeine-d6',
    'Dextromethorphan',
    'Diazepam',
    'Duloxetine',
    'Ethenylestradiol 3-glucuronide',
    'Ethinyl estradiol',
    'Hydrocodone',
    'Loratadine',
    'Norethisterone',
    'Omeprazole/Esomeprazole mix',
    'Paroxetine',
    'Penciclovir',
    'Pentoxifylline',
    'Prednisolone',
    'Prednisone',
    'Promethazine',
    'Quinine',
    'Ranitidine',
    'Sertraline',
    'Tamoxifen',
    'Tramadol',
    'Valacyclovir',
    'Venlafaxine',
    '16-Epiestriol-d2',
    '1,2-Benzenedicarboxamide',
    '1,7-Dimethylxanthine',
    '(1R,2S,5R)-Menthol'
]);
UPDATE c_category 
SET characteristic_group = 'Polychlorinated Compounds' 
WHERE characteristicname ILIKE ANY (ARRAY[
    '2,2'',3,3'',4,4'',5,6-Octachlorobiphenyl',
    '2,2'',3,3'',4,4'',5,6''-Octachlorobiphenyl',
    '2,2'',3,3'',4,4'',6,6''-Octachlorobiphenyl',
    '2,2'',3,3'',4,4'',6-Heptachlorobiphenyl',
    '2,2'',3,3'',4,4''-Hexachlorobiphenyl',
    '2,2'',3,3'',4,5,5'',6,6''-Nonachlorobiphenyl',
    '2,2'',3,3'',4,5,5'',6-Octachlorobiphenyl',
    '2,2'',3,3'',4,5,5''-Heptachlorobiphenyl',
    '2,2'',3,3'',4,5,6,6''-Octachlorobiphenyl',
    '2,2'',3,3'',4,5'',6-Heptachlorobiphenyl',
    '2,2'',3,3'',4,5'',6''-Heptachlorobiphenyl',
    '2,2'',3,3'',4,5,6''-Heptachlorobiphenyl',
    '2,2'',3,3'',4,5-Hexachlorobiphenyl',
    '2,2'',3,3'',4,5''-Hexachlorobiphenyl',
    '2,2'',3,3'',4,6,6''-Heptachlorobiphenyl',
    '2,2'',3,3'',4,6-Hexachlorobiphenyl',
    '2,2'',3,3'',4,6''-Hexachlorobiphenyl',
    '2,2'',3,3'',4-Pentachlorobiphenyl',
    '2,2'',3,3'',5,5'',6,6''-Octachlorobiphenyl',
    '2,2'',3,3'',5,5'',6''-Heptachlorobiphenyl',
    '2,2'',3,3'',5,5''-Hexachlorobiphenyl'
]);
UPDATE c_category 
SET characteristic_group = 'Heavy Metals and Metalloids' 
WHERE characteristicname ILIKE ANY (ARRAY[
    'Aluminum',
    'Antimony', 
    'Arsenic',
    'Barium',
    'Bismuth',
    'Boron',
    'Cadmium',
    'Calcium',
    'Chromium',
    'Chromium-51',
    'Copper',
    'Dysprosium',
    'Europium',
    'Gadolinium',
    'Gallium',
    'Iron',
    'Lead',
    'Lead-210',
    'Lithium',
    'Manganese',
    'Mercury',
    'Molybdenum',
    'Nickel',
    'Polonium-210',
    'Potassium',
    'Rubidium',
    'Samarium',
    'Selenium',
    'Silver',
    'Strontium',
    'Thallium',
    'Titanium',
    'Uranium',
    'Vanadium',
    'Yttrium',
    'Zinc'
]);
UPDATE c_category 
SET characteristic_group = 'Physical and Chemical Properties' 
WHERE characteristicname ILIKE ANY (ARRAY[
    'Absorbance at 280 nanometers',
    'Absorbance at 370 nanometers',
    'Absorbance at 412 nm',
    'Absorbance at 440 nm',
    'Absorption spectral slope (Sag)',
    'Acidity, (H+)',
    'Alkalinity, carbonate',
    'Alkalinity, total',
    'Biochemical oxygen demand, standard conditions',
    'BOD, ultimate',
    'Carbonaceous biochemical oxygen demand, standard conditions',
    'Chemical oxygen demand',
    'Cloud cover',
    'Color',
    'Conductivity',
    'Density at sigma-t',
    'Density as sigma-t',
    'Depth',
    'Depth, bottom',
    'Depth of water column',
    'Dissolved oxygen (DO)',
    'Dissolved oxygen saturation',
    'Extract volume',
    'Flow',
    'Flow rate, instantaneous',
    'Light attenuation coefficient',
    'Light, (PAR at depth/PAR at surface) x 100',
    'Optical density',
    'Particle size',
    'pH',
    'Salinity',
    'Specific conductance',
    'Specific UV Absorbance at 254 nm',
    'Temperature, water',
    'Total dissolved solids',
    'Total hardness',
    'Total suspended solids',
    'Turbidity',
    'Turbidity Field',
    'Water Odor (choice list)',
    'Water surface slope longitudinally',
    'Suspended Sediment Concentration',
    'Suspended Sediment Mass',
    'Bottle or bag sampler material (construction)'
]);
UPDATE c_category 
SET characteristic_group = 'Biological Indicators' 
WHERE characteristicname ILIKE ANY (ARRAY[
    'Algae, substrate rock/bank cover (choice list)',
    'BacR DNA marker',
    'Bioluminescent yeast estrogen screen (BLYES)',
    'Coliphage',
    'Cylindrospermopsin gene cyrA',
    'Cylindrospermopsins',
    'Deoxynivalenol',
    'DG3 DNA marker',
    'HF183 DNA marker',
    'Microcystin/nodularin genes mcyE/ndaF',
    'Microcystis-specific Microcystin (MC) mcyE gene',
    'Phaeophytin - Periphyton (attached)',
    'Phaeophytin - Phytoplankton (suspended)',
    'Phytoplankton biovolume',
    'Phytoplankton Density',
    'Saxitoxin gene sxtA',
    'Saxitoxins',
    'Total microcystins plus nodularins',
    'Pheophytin a',  -- Added from list two
    'Chlorophyll a',  -- Added from list two
    'Depth, Secchi disk depth',  -- Added from list two
    'Pheophytin ratio'  -- Added from list two
]);
UPDATE c_category 
SET characteristic_group = 'Nutrients and Inorganics' 
WHERE characteristicname ILIKE ANY (ARRAY[
    'Alkalinity',
    'Ammonia',
    'Ammonium',
    'Bicarbonate',
    'Carbonate',
    'Hardness, Ca, Mg',
    'Nitrate',
    'Nitrite',
    'Phosphate-phosphorus',
    'Polyphosphate',  -- From list one
    'Sulfate',
    'Total Nitrogen, mixed forms',
    'Total Phosphorus, mixed forms',
    'Chloride',  -- From list one
    'Particulate Organic Nitrogen and Particulate Nitrogen',  -- From list one
    'Ammonia and ammonium'  -- From list one
]);
Halogenated_Compounds = [
    'Perfluoro(2-propoxypropanoate)',
    'Perfluorobutanesulfonate',
    'Perfluorobutanesulfonic acid',
    'Perfluorobutanoate',
    'Perfluorodecanesulfonate',
    'Perfluorodecanoate',
    'Perfluorooctanesulfonate',
    'Perfluorooctanoic acid',
    '1,1,1,2-Tetrachloroethane',
    '1,1,1-Trichloroethane',
    '1,1,2-Trichloroethane',
    '1,1-Dichloroethane',
    '1,1-Dichloropropanone',
    '1,2-Dichloropropane',
    '1,3-Dichloropropane',
    '1,2,4-Trichlorobenzene',
    '1,2-Dibromo-3-chloropropane',
    '1,3-Dioxane',
    '1,3-Dioxolane',
    '1,4-Dioxane',
    '1-Bromo-3-chloropropane-d6',
    '1rs Cis-Permethrin',
    '2,4-D',
    '2,4-D-d3',
    '2-Chloro-4,6-diamino-s-triazine',
    '2-Chloro-4-isopropylamino-6-amino-s-triazine',
    '2-Choro-6-ethylamino-4-amino-s-triazine',
    'Atrazine',
    'Acetochlor',
    'Acetochlor ESA',
    'Acetochlor OA',
    'Acetochlor-d11'
]
Environmental_Conditions = [
    'Precipitation',
    'Precipitation 48hr prior to monitoring event (choice list)',
    'Initial sample volume',
    'Light, path',
    'Temperature, air',
    'Volume, total',
    'Precipitation during activity (choice list)',
    'Precipitation event duration',
    'RBP2, Weather Condition, Past 24 Hours (choice list)',
    'Tide stage',
    'Relative Air Temperature (choice list)',
    'Relative humidity',
    'Stream condition (text)',
    'Wave height',
    'Tide stage (choice list)',
    'Weather comments (text)',
    'Wind Condition',
    'Wind Condition (choice list)',
    'Sediment and Soil Characteristics',
    'Sediment',
    'Sand',
    'Silica',
    'Silt',
    'Solids',
    'Total Particulate Carbon',
    'Total Particulate Nitrogen',
    'Total Particulate Phosphorus'
]

Microbial and Biological Indicators = ['Cylindrospermopsin',
 'Dolichospermum-specific microcystin (MC) mcyE gene',
 'Enterococcus',
 'Escherichia coli',
 'Fecal Coliform',
 'Microcystins',
 'Planktothrix-specific microcystin (MC) mcyE gene']

Steroids and Hormones = ['11-KetoTestosterone',
 '17.alpha.-Estradiol',
 '17.beta.-Estradiol-13,14,15,16,17,18-13C6',
 '17-beta-Estradiol 17-glucuronide',
 '17-beta-Estradiol 17-sulfate',
 '17-beta-Estradiol 3-sulfate',
 '5a-Dihydrotestosterone',
 '5-alpha-Androstanedione',
 'Estradiol',
 'Estriol',
 'Estrone',
 'Testosterone',
 'Testosterone glucuronide',
 'Testosterone sulfate'
]


UPDATE c_category 
SET characteristic_group = 'Hydrocarbons' 
WHERE characteristicname ILIKE ANY (ARRAY[
    '1,2,3,4-Tetrahydronaphthalene',
    '1,2-Dimethylnaphthalene',
    '1,6,7-Trimethylnaphthalene',
    '1,6-Dimethylnaphthalene',
    '1-Methylfluorene',
    '1-Methylnaphthalene',
    '1-Methylphenanthrene',
    '1-Methylpyrene',
    '2,3,6-Trimethylnaphthalene',
    '2-Ethylnaphthalene',
    '3,3\'-Dichlorobiphenyl',
    '3,4-Dichlorobiphenyl',
    '3,4-Dichlorophenyl isocyanate'
]);def assign_category(characteristicname):
    if characteristicname in organic_compounds:
        return 'Organic Compounds'
    elif characteristicname in Pesticides_Herbicides:
        return 'Pesticide and Herbicide'
    elif characteristicname in Pharmaceuticals:
        return 'Pharamceutical/Personal Care Products'
    elif characteristicname in Heavy_Metals:
        return 'Heavy metals and Inorganics'
    elif characteristicname in Physical_Chemical:
        return 'Physcial and Chemical Properties'
    elif characteristicname in Halogenated_Compounds:
        return 'Halogenated Compounds'
    elif characteristicname in Environmental_Conditions:
        return 'Environmental Conditions'
    else:
        return 'Miscellaneous Compounds'


df['characteristicgroup']=df['characteristicname'].apply(assign_category)

dataset = df
